#define CHAR_TEX_ANTLION 'A'
#define CHAR_TEX_BLOODYFLESH 'B'
#define CHAR_TEX_CONCRETE 'C'
#define CHAR_TEX_DIRT 'D'
#define CHAR_TEX_EGGSHELL 'E' ///< the egg sacs in the tunnels in ep2.
#define CHAR_TEX_FLESH 'F'
#define CHAR_TEX_GRATE 'G'
#define CHAR_TEX_ALIENFLESH 'H'
#define CHAR_TEX_CLIP 'I'
	//#define CHAR_TEX_UNUSED 'J'
#define CHAR_TEX_SNOW 'K'
#define CHAR_TEX_PLASTIC 'L'
#define CHAR_TEX_METAL 'M'
#define CHAR_TEX_SAND 'N'
#define CHAR_TEX_FOLIAGE 'O'
#define CHAR_TEX_COMPUTER 'P'
	//#define CHAR_TEX_UNUSED 'Q'
#define CHAR_TEX_REFLECTIVE 'R'
#define CHAR_TEX_SLOSH 'S'
#define CHAR_TEX_TILE 'T'
	//#define CHAR_TEX_UNUSED 'U'
#define CHAR_TEX_VENT 'V'
#define CHAR_TEX_WOOD 'W'
	//#define CHAR_TEX_UNUSED 'X' ///< do not use - "fake" materials use this (ladders, wading, clips, etc)
#define CHAR_TEX_GLASS 'Y'
#define CHAR_TEX_WARPSHIELD 'Z' ///< wierd-looking jello effect for advisor shield.